### ISSUE TITLE
Color error in the (popup) list

### ISSUE THREAD

**Issue by FreePDF64** [2alin/tabFx#2] opened 2018-04-17 13:07 UTC
If I have many tabs in the list as an example and scroll down to the last entry, move the mouse back and return (sometimes several times) between the last and penultimate entry, I have a color error in the list. Please see as example the following pictures:
 
![1](https://user-images.githubusercontent.com/38452654/38871380-ff2b9d60-4250-11e8-937d-01bc3760ca2e.jpg)

![2](https://user-images.githubusercontent.com/38452654/38871385-02dad098-4251-11e8-918a-887953c599c1.jpg)

And here's a short video:

[TabFX.zip](https://github.com/2alin/tabFx/files/1919765/TabFX.zip)

I use Windows 10 Pro 64bit - and this color error is visible on all Windows PCs (MS Surface, hp-PC's, etc.).
I use the latest graphic drivers.

Kind regards,
Michael

**Comment by 2alin** [comment] 2018-04-17 19:31
Thank you for the pictures and the video, that helped me  a lot to find the reason of the problem.

I have updated the extension to v1.2 which apparently has solved your issue (and another issue with list enumeration after closing tabs from the list). You can force update reinstalling it again:

https://addons.mozilla.org/firefox/addon/tab-fx/

I already tested it on a computer that had your same problem and the issue was gone after the update. But, please let me know if the problem is solved with you as well.

**Comment by FreePDF64** [comment] 2018-04-18 04:31
Goog morning Adilson,

I notice that the new version 1.2 no longer has this error. I guess that's because of a different 
font, because the new one looks a little bit blurry on different PCs (mostly older PC's with lower graphic resolution). But that's not so bad.

Thank you for your support and your great AddOn,
Michael



Am 2018-04-17 21:31, schrieb Adilson Sandoval:

**Comment by 2alin** [comment] 2018-04-18 05:23
Good morning Michael, 

It wasn't the font, I didn't make any change on the font in this new version. 

The problem was with Windows and the way it manages web elements when there's continuous updates on them. In our case, when there was scrolling, all the elements (list items), subelements (close buttons, favicons) and properties like highlighting were constantly updating and Windows didn't handle it well.

What I did was to instruct the system to put special attention on the tabs list element and force the gpu to handle that  task of updating the list style while scrolling it (that's why old computers are showing blurry font, because their gpu is too old).

Now, if you encounter another extension that has the same problem and you want to help the developer, tell him/her that the key to fix it is the property "will-change: transform" :wink: 

And, thank you so much for let it me know about the problem and your detailed way to explain it. Have a nice day!

**Comment by 2alin** [comment] 2018-04-18 05:24
Closing the issue because the problem was fixed.

**Closed as completed** 2018-04-18 05:24 UTC
Labels: bug
